### ISSUE TITLE
dangit. lto problem

### ISSUE THREAD

**Issue by Gingeropolous** [moneroexamples/onion-monero-viewer#1]
had this problem with the explorer, but it somehow got fixed. Ubuntu 16, monero head (past day or 2?)

[100%] Linking CXX executable xmrviewer
/usr/bin/ld: thread_group.cpp.o: plugin needed to handle lto object
/tmp/cchCHrpq.ltrans14.ltrans.o: In function `rct::verRctSimple(rct::rctSig const&)':
<artificial>:(.text+0x48c0): undefined reference to `tools::thread_group::thread_group(unsigned long)'
<artificial>:(.text+0x4b66): undefined reference to `tools::thread_group::data::~data()'
<artificial>:(.text+0x4d62): undefined reference to `tools::thread_group::data::dispatch(std::function<void ()>)'
<artificial>:(.text+0x5237): undefined reference to `tools::thread_group::data::~data()'
/tmp/cchCHrpq.ltrans14.ltrans.o: In function `rct::verRct(rct::rctSig const&)':
<artificial>:(.text+0x5ad4): undefined reference to `tools::thread_group::thread_group(unsigned long)'
<artificial>:(.text+0x5efd): undefined reference to `tools::thread_group::data::sync()'
<artificial>:(.text+0x5f17): undefined reference to `tools::thread_group::data::~data()'
<artificial>:(.text+0x5f31): undefined reference to `tools::thread_group::data::~data()'
/tmp/cchCHrpq.ltrans14.ltrans.o: In function `std::unique_ptr<tools::thread_group, tools::thread_group::lazy_sync>::~unique_ptr()':
<artificial>:(.text+0x1b5): undefined reference to `tools::thread_group::data::sync()'
/tmp/cchCHrpq.ltrans26.ltrans.o: In function `void tools::thread_group::dispatch<std::_Bind<rct::(anonymous namespace)::verRangeWrapper_ (std::reference_wrapper<rct::key const>, std::reference_wrapper<rct::rangeSig const>, std::reference_wrapper<bool>)> >(std::_Bind<rct::(anonymous namespace)::verRangeWrapper_ (std::reference_wrapper<rct::key const>, std::reference_wrapper<rct::rangeSig const>, std::reference_wrapper<bool>)>&&) [clone .constprop.402]':
<artificial>:(.text+0x3c0f): undefined reference to `tools::thread_group::data::dispatch(std::function<void ()>)'
collect2: error: ld returned 1 exit status
CMakeFiles/xmrviewer.dir/build.make:121: recipe for target 'xmrviewer' failed
make[2]: *** [xmrviewer] Error 1
CMakeFiles/Makefile2:69: recipe for target 'CMakeFiles/xmrviewer.dir/all' failed
make[1]: *** [CMakeFiles/xmrviewer.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by moneroexamples** [comment]
I need time to update the viewer to work with latest monero version. It hasnt been updated in few weeks, as I though there is no interest in it, and I had problems hosting it. I will ping you on reddit when its updated.
