### ISSUE TITLE
Compilation error on FreeBSD 10

### ISSUE THREAD

**Issue by antanst** [moneroexamples/onion-monero-viewer#2]
While trying to build in FreeBSD 10:

```
Scanning dependencies of target myext
[  5%] Building CXX object ext/CMakeFiles/myext.dir/format.cc.o
error: invalid value 'c++14' in '-std=c++14'
*** Error code 1
```

FreeBSD 10.1-RELEASE clang does not support C++ 14. Is this a hard requirement?

**Comment by antanst** [comment]
On a second look, FreeBSD 10.1 includes clang 3.4.1 which supports C++ 14. I'm not sure what's going on.

**Comment by moneroexamples** [comment]
Thanks for the comment.  Crow (a http micro-framework) uses C++14 features. So without C++14 support, crow will not compile, and subesquently, the viewer. But you can try equivalent flag, e.g., `-std=c++1y` in top level CMakeLists.txt. Differnt compilers may use different flags to denote specific C++ versions.

**Comment by antanst** [comment]
Changing -std=c++14 to c++1y seems to do the trick...until the following error later (using root user is scary, I know, but it's on a VM) :

```
Scanning dependencies of target xmrviewer
[ 94%] Building CXX object CMakeFiles/xmrviewer.dir/main.cpp.o
In file included from /root/onion-monero-viewer/main.cpp:5:
In file included from /root/onion-monero-viewer/src/MicroCore.h:10:
In file included from /root/onion-monero-viewer/src/monero_headers.h:12:
In file included from /opt/monero-dev/headers/contrib/epee/include/net/http_base.h:31:
In file included from /usr/local/include/boost/regex.hpp:31:
In file included from /usr/local/include/boost/regex/v4/regex.hpp:97:
/usr/local/include/boost/regex/v4/instances.hpp:124:34: warning: unknown warning group '-Wkeyword-macro', ignored
      [-Wunknown-pragmas]
#pragma clang diagnostic ignored "-Wkeyword-macro"
                                 ^
In file included from /root/onion-monero-viewer/main.cpp:5:
In file included from /root/onion-monero-viewer/src/MicroCore.h:10:
In file included from /root/onion-monero-viewer/src/monero_headers.h:12:
In file included from /opt/monero-dev/headers/contrib/epee/include/net/http_base.h:31:
In file included from /usr/local/include/boost/regex.hpp:31:
In file included from /usr/local/include/boost/regex/v4/regex.hpp:108:
/usr/local/include/boost/regex/v4/instances.hpp:124:34: warning: unknown warning group '-Wkeyword-macro', ignored
      [-Wunknown-pragmas]
#pragma clang diagnostic ignored "-Wkeyword-macro"
                                 ^
In file included from /root/onion-monero-viewer/main.cpp:6:
/root/onion-monero-viewer/src/page.h:338:48: error: no viable conversion from 'const crypto::hash' to 'char'
                crypto::hash previous_tx_hash {null_hash};
                                               ^~~~~~~~~
/root/onion-monero-viewer/src/page.h:1734:27: error: no member named '__cxa_exception_type' in
      'std::exception_ptr'
                     << p.__cxa_exception_type()->name() << endl;
                        ~ ^
```

Clang is FreeBSD 10.1 default:

```
$ clang -v
FreeBSD clang version 3.4.1 (tags/RELEASE_34/dot1-final 208032) 20140512
Target: x86_64-unknown-freebsd10.1
Thread model: posix
Selected GCC installation: 
```

**Comment by antanst** [comment]
Closed accidentally, sorry.

**Comment by moneroexamples** [comment]
Fixed this compilation issue in latest commit. Please let me know if something more is happening. Never tried compiling it on FreeBSD before, so dont know what to expect mysql:-)

**Comment by antanst** [comment]
I'm still encountering the same error:

```
In file included from /root/onion-monero-viewer/main.cpp:6:
/root/onion-monero-viewer/src/page.h:338:48: error: no viable conversion from 'const crypto::hash' to 'char'
                crypto::hash previous_tx_hash {null_hash};
```

also later on:

```
In file included from /usr/include/c++/v1/algorithm:627:
/usr/include/c++/v1/utility:294:15: error: no viable overloaded '='
        first = __p.first;
```

**Comment by antanst** [comment]
Full log here: https://paste.fedoraproject.org/507683/81972646/

**Comment by moneroexamples** [comment]
The first issue about `crypto::hash previous_tx_hash {null_hash};` I think is fixed. The second not sure how to do, as it seems to be referencing crow and c++ std library. My guess is that crow uses some features of std not implemented yet in gcc. I will try to install freebsd on virtual box and see what I can do.

**Comment by antanst** [comment]
I confirm that the first error is fixed as per commit d495730239192b05c946b8ca7a2403fa80b8ef01. Thank you for your efforts!

**Comment by moneroexamples** [comment]
Hi. I have difficulties with installing monero on Freebsd. It complains that boost 1.58 is needed, but freebsd has older version. Did you install them yourself? I'm not very familiar with freebsd, sorry for basic questions.

**Comment by antanst** [comment]
Thankfully this isn't a hard requirement; you can change the version from the top-level CMakeLists.txt to match the ports version you have installed and it will compile and run just fine.
